container:
    image: python:latest

Deploy_task:
    only_if: $CIRRUS_BRANCH == 'master'
    env:
        DEPLOY_TOKEN: ENCRYPTED[2e1b3879f879c57eefa69d7b97272ff580fe771b21acd3ab5ccadd70942c21c717435b2756aa270c4dc960009a6fd03c]
        FETCH_TOKEN: ENCRYPTED[672acd1d9f14172fe2491fd1feae919679585cc4e33a3cca08399fec685e96e9a858f122b1150856dbaec0ddd855d575]
    install_dependencies_script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r requirements.txt
        python3 -m pip install --upgrade https://deploy%40rdil.rocks:${FETCH_TOKEN}@rdil.mycloudrepo.io/repositories/backend/mkdocs-material/mkdocs_material-6.2.2+insiders.1.13.2-py3-none-any.whl
    deploy_script: |
        git config --global user.name "Cirrus CI"
        git config --global user.name "deploy@rdil.rocks"
        git remote set-url origin https://$DEPLOY_TOKEN@github.com/rdilweb/docs/
        mkdocs gh-deploy --force --remote-branch gh-pages

task:
    name: PR Build
    only_if: $CIRRUS_PR != ""
    install_dependencies_script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r requirements-dev.txt
    build_script: |
        mkdocs build
    deploy_preview_artifacts:
        path: site
