container:
    image: python:latest

Deploy_task:
    only_if: $CIRRUS_BRANCH == 'master'
    env:
        DEPLOY_TOKEN: ENCRYPTED[6b812d37d9776bfeecfe90a09011c2d78cc5a6a1f48f4a64ca2164e00f0271db6a9cea6ca0433d9652ca27a4e221a0c8]
        FETCH_TOKEN: ENCRYPTED[672acd1d9f14172fe2491fd1feae919679585cc4e33a3cca08399fec685e96e9a858f122b1150856dbaec0ddd855d575]
    install_dependencies_script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r requirements.txt
        python3 -m pip install --upgrade https://deploy%40rdil.rocks:${FETCH_TOKEN}@rdil.mycloudrepo.io/repositories/backend/mkdocs-material/mkdocs-material-6.1.6+insiders.1.11.1.tar.gz
    deploy_script: |
        git config --global user.name "Cirrus CI"
        git config --global user.name "deploy@rdil.rocks"
        git remote set-url origin https://$DEPLOY_TOKEN@github.com/rdilweb/docs/
        mkdocs gh-deploy --force --remote-branch gh-pages

task:
    name: PR Build
    only_if: $CIRRUS_PR != ""
    install_dependencies_script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r requirements-dev.txt
    build_script: |
        mkdocs build
    deploy_preview_artifacts:
        path: site
