site_name: RDIL Docs

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'indigo'
  feature:
    tabs: false
  favicon: /favicon.ico
  logo: assets/34555510.png

repo_name: 'rdilweb/docs'
repo_url: 'https://github.com/rdilweb/docs'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - mkdocstrings

site_description: Documentation for RDIL's services and libraries.
site_url: https://docs.rdil.rocks
site_author: Reece Dunham
copyright: Copyright (©) Reece Dunham 2019-present
remote_branch: master

extra:
  social:
    - type: 'github'
      link: 'https://github.com/rdilweb'
    - type: 'twitter'
      link: 'https://twitter.com/rdil_pickle'

nav:
  - Home: index.md
  - API: api.md
  - Libraries:
    - area4: libraries/area4.md
    - bluejay:
      - Introduction: libraries/bluejay/index.md
      - discord-sentry-reporting: libraries/bluejay/discord-sentry-reporting.md
      - flask-rest-error-handling: libraries/bluejay/flask-rest-error-handling.md
      - joinstring: libraries/bluejay/joinstring.md
    - filehandlers:
        - Home: libraries/filehandlers/index.md
        - "API Reference": libraries/filehandlers/api.md
    - intutils: libraries/intutils.md
    - lcpy: libraries/lcpy.md
    - LiquidBT:
      - Introduction: libraries/liquidbt/intro.md
      - "Getting Started": libraries/liquidbt/getting-started.md
      - Plugins: libraries/liquidbt/plugins.md
    - Perf:
      - Introduction: libraries/perf/index.md
      - Patterns: libraries/perf/patterns.md
    - PickleCore: libraries/picklecore.md
    - "Static Server": libraries/static-server-rdil.md
  - Specifications:
    - DNSR: specs/dnsr.md
  - "Code of Conduct": CODE_OF_CONDUCT.md
  - "Docs License": LICENSE.md
