site_name: RDIL Docs

theme:
    name: "material"
    palette:
        - scheme: default
          primary: cyan
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
        - scheme: slate
          primary: cyan
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
    favicon: /favicon.ico
    icon:
        repo: fontawesome/brands/github
    logo: assets/images/rdil-logo.png
    font: false
    custom_dir: docs

repo_name: "rdilweb/docs"
repo_url: "https://github.com/rdilweb/docs"

markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.meta
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.magiclink:
          repo_url_shortener: true
          repo_url_shorthand: true
          social_url_shorthand: true
          user: rdilweb
          repo: docs
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tabbed

plugins:
    - search
    - git-revision-date-localized:
          type: timeago
    - minify:
          minify_html: true
    - progress
    - redirects:
          redirect_maps:
              "libraries/lcpy.md": "https://rdil.rocks/docs/lcpy"
              "libraries/area4.md": "https://area4.readthedocs.io"
              "javadocs.md": "https://rdil.rocks/docs/javadocs"
              "libraries/bluejay/discord-sentry-reporting.md": "https://rdil.rocks/docs/libraries/bluejay/discord-sentry-reporting"
              "libraries/bluejay/flask-rest-error-handling.md": "https://rdil.rocks/docs/libraries/bluejay/flask-rest-error-handling"
              "api.md": "https://rdil.rocks/docs/api"
              "libraries/filehandlers/index.md": "https://rdil.rocks/docs/libraries/filehandlers"
              "libraries/filehandlers/api.md": "https://rdil.rocks/docs/libraries/filehandlers/api"
              "libraries/intutils/index.md": "https://rdil.rocks/docs/libraries/intutils"
              "libraries/intutils/api.md": "https://rdil.rocks/docs/libraries/intutils/api"
              "libraries/parse-repr.md": "https://rdil.rocks/docs/libraries/parse-repr"
              "specs/dnsr.md": "https://rdil.rocks/docs/specifications/dnsr"
              "SECURITY.md": "https://rdil.rocks/docs/security"
              "about/me.md": "https://rdil.rocks/docs/about/me"
              "about/rdilweb.md": "https://rdil.rocks/docs/about/rdilweb"
              "libraries/static-server-rdil.md": "https://rdil.rocks/docs/libraries/static-server-rdil"
              "libraries/mkdocs-plugin-progress.md": "https://rdil.rocks/docs/libraries/mkdocs-plugin-progress"
              "about/support-policy.md": "https://rdil.rocks/docs/support-policy"

site_description: Documentation for RDIL's services and libraries.
site_url: https://docs.rdil.rocks
site_author: Reece Dunham
copyright: Copyright (©) Reece Dunham 2019-present.
remote_branch: master

extra:
    social:
        - icon: "fontawesome/solid/home"
          link: "https://rdil.rocks/"
        - icon: "fontawesome/brands/github"
          link: "https://github.com/rdil/"
        - icon: "fontawesome/brands/gitlab"
          link: "https://gitlab.com/rdil/"
        - icon: "fontawesome/brands/twitter"
          link: "https://twitter.com/rdil_pickle/"

extra_css:
    - assets/stylesheets/rdil.css

nav:
    - Libraries:
          - PickleCore: libraries/picklecore.md
    - Specifications:
          - "Tar Command": specs/tar.md
    - Tutorials:
          - "better-wsfull": tutorials/better-wsfull/index.md
          - "Cirrus Builder": tutorials/cirrusbuilder/index.md
    - About:
          - "Code of Conduct": CODE_OF_CONDUCT.md
